### ISSUE TITLE
CUDA Runtime Not Found During Docker Build Process

### ISSUE THREAD

**Issue by kevinhu22** [TUMFTM/DPFT#3]
Hi,
While building the Docker image for the repository, I encountered an issue where the CUDA runtime could not be found. The build process fails with the following error message:

    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
    Traceback (most recent call last):
      File "/app/Deformable-DETR-main/models/ops/setup.py", line 69, in <module>
        ext_modules=get_extensions(),
      File "/app/Deformable-DETR-main/models/ops/setup.py", line 47, in get_extensions
        raise NotImplementedError('Cuda is not availabel')
    NotImplementedError: Cuda is not availabel

I followed the guide from the FAQ section regarding this error, but the issue persists. As a temporary workaround, I have removed the Dockerfile download of the repository Deformable-DETR. Instead, I download the repository after the Docker container is running.

**Comment by ffent** [comment]
Hi @kevinhu22 ,

thanks for reporting this issue. To reproduce your error, it would be great if you could provide some more details on the system used to build the docker image. Could you please provide details on the `Ubuntu `and `docker `version that you are using and if `docker-ce`, `docker-ce-cli`, `docker-buildx-plugin` and `docker-compose-plugin` packages are installed?

**Comment by kevinhu22** [comment]
Hey @ffent , 

Thank you for your response! I am currently using Ubuntu 22.04.4 LTS and Docker Engine - Community version 27.3.1. 
I have also verified that all Docker components are installed on my system. 

Best regards, 
Kevin

**Comment by ffent** [comment]
Hi @kevinhu22,

the issue could have been reproduced and solved with the following procedure.


1. Install nvidia-container-runtime
    ```
    sudo apt-get install nvidia-container-runtime
    ```

2. Edit/create the /etc/docker/daemon.json with content:
    ```
    {
        "runtimes": {
            "nvidia": {
                "path": "/usr/bin/nvidia-container-runtime",
                "runtimeArgs": []
            } 
        },
        "default-runtime": "nvidia" 
    }
    ```
3. Remove Docker CLI plugin for extended build capabilities:
    ```
    sudo apt remove docker-buildx-plugin
    ```

4. Restart docker daemon:
    ```
    sudo systemctl restart docker
    ```

5. Build Docker image:
    ```
    docker build -t dprt:0.0.1 .
    ```

    Reference: https://stackoverflow.com/questions/59691207/docker-build-with-nvidia-runtime


This procedure has been added to the FAQ section in the README, which is why the issue will be closed. If the problems persist, feel free to reopen the issue.
